# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
%YAML 1.2
---
$id: http://devicetree.org/schemas/arm/sunxi/allwinner,sun6i-a31-cpuconfig.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

title: Allwinner CPU Configuration Controller Device Tree Bindings

maintainers:
  - Chen-Yu Tsai <wens@csie.org>
  - Maxime Ripard <mripard@kernel.org>

properties:
  compatible:
    enum:
      - allwinner,sun6i-a31-cpuconfig
      - allwinner,sun8i-a23-cpuconfig
      - allwinner,sun8i-a83t-cpucfg
      - allwinner,sun8i-a83t-r-cpucfg
      - allwinner,sun9i-a80-cpucfg

  reg:
    maxItems: 1

required:
  - compatible
  - reg

additionalProperties: false

examples:
  - |
      cpucfg@1f01c00 {
          compatible = "allwinner,sun6i-a31-cpuconfig";
          reg = <0x01f01c00 0x300>;
      };

...
