# SPDX-License-Identifier: GPL-2.0

msrv = "1.78.0"

check-private-items = true

disallowed-macros = [
    # The `clippy::dbg_macro` lint only works with `std::dbg!`, thus we simulate
    # it here, see: https://github.com/rust-lang/rust-clippy/issues/11303.
    { path = "kernel::dbg", reason = "the `dbg!` macro is intended as a debugging tool" },
]
