image: ayufan/rock64-dockerfiles:x86_64

variables:
  GITHUB_USER: ayufan-rock64
  GITHUB_REPO: linux-mainline-kernel

  USE_CCACHE: "true"
  CCACHE_DIR: "/data/shared/ccache"

stages: [build]

before_script:
  - ccache -M 0 -F 0

build:
  stage: build
  only: [branches]
  script:
    - export RELEASE=$((1000+$CI_PIPELINE_IID))
    - ./dev-make kernel-package
    - |
      set -x

      export RELEASE_NAME="$(./dev-make version)"
      export RELEASE_TITLE="$(./dev-make version)"
      export DESCRIPTION="$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"

      github-release release \
        --tag "${RELEASE_NAME}" \
        --name "${RELEASE_TITLE}" \
        --description "${DESCRIPTION}" \
        --target "${CI_COMMIT_SHA}" \
        --draft

      for i in ../*$(./dev-make info)*.deb; do
        github-release upload \
          --tag "${RELEASE_NAME}" \
          --name "$(basename "${i}")" \
          --file "${i}"
      done

      github-release edit \
        --tag "${RELEASE_NAME}" \
        --name "${RELEASE_TITLE}" \
        --description "${DESCRIPTION}"

      rm ../*$(./dev-make info)*.deb
