on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install native dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ditaa graphviz
      - name: Install pip dependencies
        run: sudo pip install Sphinx==1.6.7 sphinx_rtd_theme hieroglyph==1.0
      - name: Build documentation
        run: cd tools/labs && make docs
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: Documentation/output/teaching
      - name: Publish linux-kernel-labs.gihub.io
        env:
          URL: https://api.github.com/repos/linux-kernel-labs/linux-kernel-labs.github.io/dispatches
          HASH: yxg-obg:q8qqs27s1617p99n2p131s71n827npn1on4445q3 
        run: |
          curl -X POST -u $(tr a-zA-Z n-za-mN-ZA-M <<<"$HASH") --header 'content-type: application/json' $URL \
          --data '{"event_type" : "publish", "client_payload" : { "run_id" : "${{ github.run_id }}", "dir" : "${{ github.ref }}" } }'
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          HASH: yxg-obg:q8qqs27s1617p99n2p131s71n827npn1on4445q3 
        run: |
          curl -X POST -u $(tr a-zA-Z n-za-mN-ZA-M <<<"$HASH") --header 'content-type: application/json' $URL \
          --data '{"body" : "Published at http://linux-kernel-labs.github.io/${{ github.ref }}"}'
